language: generic

sudo: required

services:
  - docker
  
before_install:
  - docker pull makarius/isabelle:Isabelle2017
  
script:
  - docker run --mount type=bind source=kathode/ destination=/kathode readonly=true makarius/isabelle:Isabelle2017 build -d /kathode/isabelle-theories -l Test
