language: generic

sudo: required

services:
  - docker
  
before_install:
  - docker pull makarius/isabelle:Isabelle2017
  
script:
  - bash -c 'echo $HOME'
  - bash -c 'echo $TRAVIS_BUILD_DIR'
  - bash -c 'ls -las'
  - docker run --mount type=bind,source=$TRAVIS_BUILD_DIR,target=/repo,readonly makarius/isabelle:Isabelle2017 build -d /repo -l Test
