language: generic

sudo: required

services:
  - docker
  
before_install:
  - docker pull makarius/isabelle:Isabelle2017
  
script:
  - docker run -v kathode:/kathode --entrypoint "/bin/bash" makarius/isabelle:Isabelle2017 ls -l
