language: generic

install: 
  - if [ ! -d Isabelle2016-1 ]; then wget https://isabelle.in.tum.de/dist/Isabelle2016-1_app.tar.gz; tar -xzf Isabelle2016-1_app.tar.gz; fi
  - ls Isabelle2016-1
  - Isabelle2016-1/bin/isabelle build -d. -l HOL
  
cache:
  directories:
    - Isabelle2016-1
    
script:
  - Isabelle2016-1/bin/isabelle build -d. -l Test
