language: generic

sudo: required

services:
  - docker
  
before_install:
  - docker pull makarius/isabelle:Isabelle2017
  
script:
  - docker run -v kathode:/kathode makarius/isabelle:Isabelle2017 
  - docker exec makarius/isabelle:Isabelle2017 ls -l
