language: generic

sudo: required

services:
  - docker
  
before_install:
  - docker pull makarius/isabelle:Isabelle2017
  
script:
  - docker run makarius/isabelle:Isabelle2017 build -d ./isabelle-theories -l Test
